# Generated by Django 5.0.6 on 2024-07-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foto_video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='type',
            field=models.CharField(choices=[('avi', 'avi'), ('mpeg', 'mpeg'), ('wmv', 'gif'), ('mp4', 'mp4')], max_length=5),
        ),
    ]
